### ISSUE TITLE
Feature Request: Sense V2 Motion and Contact Sensors

### ISSUE THREAD

**Issue by douglaslinsmeyer** [SecKatie/wyzeapy#84]
I've validated that they are showing in the API's.

For contact sensors, the property that determines open/closed is pid: P1301, 1 = open and 0 = closed

**Comment by brg468** [comment]
I think these properties are already included in this lib, but they are not added to Homeassistant for the reasons described here. 

https://github.com/SecKatie/ha-wyzeapi/issues/320#issuecomment-1001523837
